### ISSUE TITLE
Gurobi

### ISSUE THREAD

**Issue by WPSlacker** [aothman/hiscore#4]
Dear HiScore Member, are there any plans for a branch that does not use Gurobi optimization?  Perhaps a limited functionality branch that uses a open optimization package?

Gurobi has a $12,000 license fee, and for non-academics doing independent research, or early start-ups, this is prohibitively expensive.

Thanks, and I'm excited to try out your repo!

**Comment by aothman** [comment]
Thank you for the comment. Yes, I am very interested in replacing gurobi with a free solution.

In HiScore, Gurobi is used to solve a quadratic program (QP) with linear constraints. So far I have not found a free QP solver for python that is widely and easily distributed and involves expressing the optimization problem in a straightforward way.

Any suggestions from the community would be appreciated!

**Comment by WPSlacker** [comment]
Yes, my cursory search also showed nothing.  I find this strange considering the mass of enthusiasts for numpy and scipy.  Perhaps a better approach would be going straight to C with the libraries it offers?
http://sigpromu.org/quadprog/
http://doc.cgal.org/latest/QP_solver/index.html

I wouldn't mind tackling the problem, but I'm a noob, and it will take several months before I can manage something of this caliber.

Thanks!

**Comment by aothman** [comment]
It looks like cvxpy may be a good solution here: http://www.cvxpy.org/en/latest/ . It supports QP, is free, and is distributed on PyPI. I'll experiment with it.

**Comment by WPSlacker** [comment]
It looks nice.  I am still new to python, but if there is any way that I can help, please let me know!

**Comment by aothman** [comment]
Please take a look at the new **cvxpy** branch. I'll be testing it further in the next couple days before merging it into master.

**Comment by WPSlacker** [comment]
Yes, I've done some initial tests and everything looks good.  I will come up with some more tests.  Thanks!

**Comment by aothman** [comment]
Allright, this is now merged into the master branch. Please open a new issue if you see problems!

**Comment by WPSlacker** [comment]
I tried it on several examples, today.  It worked perfectly.  Every data scientist should have this in their toolkit.  Thanks so much!
